import { CardDefinition, DeckDefinition } from "@/lib/game/types";

const art = (id: string) => `cards/${id}.webp`;

export const cardCatalog: Record<string, CardDefinition> = {
  thief: {
    id: "thief",
    name: "لص",
    role: "investigator",
    faction: "فريق المافيا",
    image: art("thief"),
    cost: 1,
    attack: 1,
    health: 2,
    text: "عند النزول: اسحب بطاقة.",
    battlecry: { type: "draw_card", amount: 1 },
    palette: { accent: "#38bdf8", glow: "rgba(56, 189, 248, 0.35)" },
  },
  alley_doctor: {
    id: "alley_doctor",
    name: "طبيب الحارة",
    role: "medic",
    faction: "النجاة",
    image: art("alley_doctor"),
    cost: 2,
    attack: 2,
    health: 3,
    text: "عند النزول: عالج بطلك 2.",
    battlecry: { type: "heal_friendly_hero", amount: 2 },
    palette: { accent: "#34d399", glow: "rgba(52, 211, 153, 0.32)" },
  },
  shadow_blade: {
    id: "shadow_blade",
    name: "نصل الظل",
    role: "killer",
    faction: "العصبة السوداء",
    image: art("shadow_blade"),
    cost: 3,
    attack: 4,
    health: 2,
    text: "اندفاع.",
    keywords: ["charge"],
    palette: { accent: "#f97316", glow: "rgba(249, 115, 22, 0.35)" },
  },
  iron_guard: {
    id: "iron_guard",
    name: "حارس الحديد",
    role: "guardian",
    faction: "الحماية",
    image: art("iron_guard"),
    cost: 3,
    attack: 2,
    health: 5,
    text: "استفزاز.",
    keywords: ["taunt"],
    palette: { accent: "#94a3b8", glow: "rgba(148, 163, 184, 0.34)" },
  },
  rumor_spinner: {
    id: "rumor_spinner",
    name: "ناسج الشائعات",
    role: "trickster",
    faction: "الظل الناعم",
    image: art("rumor_spinner"),
    cost: 2,
    attack: 3,
    health: 2,
    text: "عند النزول: زد هجوم حليف +1 وصحته +1.",
    battlecry: { type: "buff_friendly_minion", amount: 1 },
    palette: { accent: "#f472b6", glow: "rgba(244, 114, 182, 0.33)" },
  },
  district_scout: {
    id: "district_scout",
    name: "كشاف المقاطعة",
    role: "investigator",
    faction: "قسم الأدلة",
    image: art("district_scout"),
    cost: 2,
    attack: 2,
    health: 2,
    text: "عند النزول: ألحق 1 بزعيم العدو.",
    battlecry: { type: "damage_enemy_hero", amount: 1 },
    palette: { accent: "#22d3ee", glow: "rgba(34, 211, 238, 0.34)" },
  },
  night_sniper: {
    id: "night_sniper",
    name: "قناص الليل",
    role: "killer",
    faction: "العصبة السوداء",
    image: art("night_sniper"),
    cost: 4,
    attack: 3,
    health: 3,
    text: "عند النزول: ألحق 2 بأضعف وحدة عدوة.",
    battlecry: { type: "damage_enemy_minion", amount: 2 },
    palette: { accent: "#fb7185", glow: "rgba(251, 113, 133, 0.33)" },
  },
  field_nurse: {
    id: "field_nurse",
    name: "ممرضة الميدان",
    role: "medic",
    faction: "النجاة",
    image: art("field_nurse"),
    cost: 4,
    attack: 3,
    health: 4,
    text: "عند النزول: استدعِ مساعد إسعاف 1/1.",
    battlecry: { type: "summon_token", tokenCardId: "medic_token" },
    palette: { accent: "#10b981", glow: "rgba(16, 185, 129, 0.35)" },
  },
  masked_judge: {
    id: "masked_judge",
    name: "القاضي المقنع",
    role: "guardian",
    faction: "الميزان",
    image: art("masked_judge"),
    cost: 5,
    attack: 4,
    health: 6,
    text: "استفزاز.",
    keywords: ["taunt"],
    palette: { accent: "#eab308", glow: "rgba(234, 179, 8, 0.35)" },
  },
  mastermind: {
    id: "mastermind",
    name: "العقل المدبر",
    role: "trickster",
    faction: "الظل الناعم",
    image: art("mastermind"),
    cost: 5,
    attack: 4,
    health: 4,
    text: "عند النزول: اسحب بطاقة وألحق 1 بزعيم العدو.",
    battlecry: { type: "draw_card", amount: 1 },
    palette: { accent: "#a78bfa", glow: "rgba(167, 139, 250, 0.34)" },
  },
  rooftop_hunter: {
    id: "rooftop_hunter",
    name: "صياد السطح",
    role: "killer",
    faction: "العصبة السوداء",
    image: art("rooftop_hunter"),
    cost: 6,
    attack: 6,
    health: 5,
    text: "عند النزول: ألحق 2 بزعيم العدو.",
    battlecry: { type: "damage_enemy_hero", amount: 2 },
    palette: { accent: "#ef4444", glow: "rgba(239, 68, 68, 0.34)" },
  },
  civic_captain: {
    id: "civic_captain",
    name: "قائد الحي",
    role: "civilian",
    faction: "السكان",
    image: art("civic_captain"),
    cost: 4,
    attack: 4,
    health: 5,
    text: "وحدة متوازنة تفرض وجودها.",
    palette: { accent: "#60a5fa", glow: "rgba(96, 165, 250, 0.35)" },
  },
  undercover_agent: {
    id: "undercover_agent",
    name: "عميل متخفي",
    role: "investigator",
    faction: "قسم الأدلة",
    image: art("undercover_agent"),
    cost: 3,
    attack: 3,
    health: 3,
    text: "عند النزول: ألحق 2 بأضعف وحدة عدوة.",
    battlecry: { type: "damage_enemy_minion", amount: 2 },
    palette: { accent: "#06b6d4", glow: "rgba(6, 182, 212, 0.34)" },
  },
  safehouse_keeper: {
    id: "safehouse_keeper",
    name: "حارس الملاذ",
    role: "guardian",
    faction: "الحماية",
    image: art("safehouse_keeper"),
    cost: 2,
    attack: 1,
    health: 4,
    text: "استفزاز.",
    keywords: ["taunt"],
    palette: { accent: "#cbd5e1", glow: "rgba(203, 213, 225, 0.35)" },
  },
  whisper_broker: {
    id: "whisper_broker",
    name: "سمسار الهمس",
    role: "trickster",
    faction: "الظل الناعم",
    image: art("whisper_broker"),
    cost: 1,
    attack: 1,
    health: 1,
    text: "عند النزول: زد هجوم حليف +1 وصحته +1.",
    battlecry: { type: "buff_friendly_minion", amount: 1 },
    palette: { accent: "#f9a8d4", glow: "rgba(249, 168, 212, 0.35)" },
  },
  medic_token: {
    id: "medic_token",
    name: "مساعد إسعاف",
    role: "medic",
    faction: "النجاة",
    image: art("medic_token"),
    cost: 1,
    attack: 1,
    health: 1,
    text: "وحدة دعم صغيرة.",
    palette: { accent: "#6ee7b7", glow: "rgba(110, 231, 183, 0.35)" },
  },
};

export const decks: DeckDefinition[] = [
  {
    id: "city_watch",
    name: "حراس المدينة",
    theme: "سيطرة ودفاع وسحب بطاقات ثابت",
    heroTitle: "قائد المراقبة",
    summary: "يركز على التحمل وبناء لوح متين ثم إنهاء المباراة بالتفوق العددي.",
    cardIds: [
      "thief",
      "thief",
      "safehouse_keeper",
      "safehouse_keeper",
      "alley_doctor",
      "district_scout",
      "district_scout",
      "undercover_agent",
      "undercover_agent",
      "iron_guard",
      "iron_guard",
      "field_nurse",
      "field_nurse",
      "civic_captain",
      "masked_judge",
      "masked_judge",
    ],
  },
  {
    id: "midnight_syndicate",
    name: "عصبة منتصف الليل",
    theme: "هجوم أسرع وضغط مباشر على الزعيم",
    heroTitle: "زعيم العصبة",
    summary: "دك هجومي يستخدم الاندفاع والضرر المباشر لكسر إيقاع الخصم بسرعة.",
    cardIds: [
      "whisper_broker",
      "whisper_broker",
      "rumor_spinner",
      "rumor_spinner",
      "shadow_blade",
      "shadow_blade",
      "district_scout",
      "night_sniper",
      "night_sniper",
      "undercover_agent",
      "undercover_agent",
      "civic_captain",
      "mastermind",
      "mastermind",
      "rooftop_hunter",
      "rooftop_hunter",
    ],
  },
  {
    id: "veil_council",
    name: "مجلس الستار",
    theme: "خدع متوازنة وتبديلات ذكية",
    heroTitle: "صانع القرارات",
    summary: "يمزج الحماية مع التلاعب الخفيف باللوح ويحافظ على الضغط التدريجي.",
    cardIds: [
      "thief",
      "whisper_broker",
      "safehouse_keeper",
      "alley_doctor",
      "rumor_spinner",
      "rumor_spinner",
      "undercover_agent",
      "iron_guard",
      "field_nurse",
      "field_nurse",
      "night_sniper",
      "civic_captain",
      "civic_captain",
      "masked_judge",
      "mastermind",
      "rooftop_hunter",
    ],
  },
];

export function getDeck(deckId: string): DeckDefinition {
  const deck = decks.find((item) => item.id === deckId);
  if (!deck) {
    throw new Error(`Unknown deck: ${deckId}`);
  }

  return deck;
}
